site_name: funtracks

site_url: https://funkelab.github.io/funtracks/

theme:
  name: "material"
  palette:
    scheme: slate
    primary: purple
    accent: purple
  features:
    - navigation.indexes

extra:
  version:
    provider: mike
    default: latest

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_section_style: table # list # or "table"
          docstring_style: "google"
          heading_level: 3
          merge_init_into_class: true
          # parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_source: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # summary: true
          show_docstring_attributes: true
          show_attribute_values: true
          show_labels: false
- api-autonav:
    modules: ['src/funtracks/']
